import { SessionDifficulty } from './session.entity';

export type SessionWord = {
  term: string;
  definition: string;
  example: string;
  difficulty: SessionDifficulty;
};

export const SESSION_WORDS: SessionWord[] = [
  {
    term: 'cup',
    definition: 'a small container used for drinking',
    example: 'She filled the ???? with water.',
    difficulty: SessionDifficulty.A1,
  },
  {
    term: 'chair',
    definition: 'a seat with a back for one person',
    example: 'He pulled the ???? closer to the table.',
    difficulty: SessionDifficulty.A1,
  },
  {
    term: 'train',
    definition: 'a long line of vehicles on rails for travel',
    example: 'The ???? arrived at noon.',
    difficulty: SessionDifficulty.A1,
  },
  {
    term: 'store',
    definition: 'a place where you buy things',
    example: 'We stopped at the ???? for bread.',
    difficulty: SessionDifficulty.A1,
  },
  {
    term: 'street',
    definition: 'a public road in a city or town',
    example: 'They walked down the ????.',
    difficulty: SessionDifficulty.A1,
  },
  {
    term: 'window',
    definition: 'an opening in a wall that lets in light',
    example: 'Please close the ????.',
    difficulty: SessionDifficulty.A1,
  },
  {
    term: 'money',
    definition: 'coins or paper used to buy things',
    example: 'I do not have enough ????.',
    difficulty: SessionDifficulty.A1,
  },
  {
    term: 'phone',
    definition: 'a device used to call people',
    example: 'My ???? is on the desk.',
    difficulty: SessionDifficulty.A1,
  },
  {
    term: 'happy',
    definition: 'feeling pleased or glad',
    example: 'She is ???? today.',
    difficulty: SessionDifficulty.A1,
  },
  {
    term: 'cold',
    definition: 'having a low temperature',
    example: 'The water is ????.',
    difficulty: SessionDifficulty.A1,
  },
  {
    term: 'borrow',
    definition: 'to take something for a short time',
    example: 'Can I ???? your pen?',
    difficulty: SessionDifficulty.A2,
  },
  {
    term: 'quiet',
    definition: 'making very little noise',
    example: 'The library is ????.',
    difficulty: SessionDifficulty.A2,
  },
  {
    term: 'arrive',
    definition: 'to reach a place',
    example: 'We ???? at the airport early.',
    difficulty: SessionDifficulty.A2,
  },
  {
    term: 'choose',
    definition: 'to decide between options',
    example: 'Pick a color and ???? a size.',
    difficulty: SessionDifficulty.A2,
  },
  {
    term: 'return',
    definition: 'to come or go back',
    example: 'I will ???? the book tomorrow.',
    difficulty: SessionDifficulty.A2,
  },
  {
    term: 'friendly',
    definition: 'kind and pleasant',
    example: 'Our neighbors are ????.',
    difficulty: SessionDifficulty.A2,
  },
  {
    term: 'message',
    definition: 'a note or piece of information sent to someone',
    example: 'I sent a ???? to my teacher.',
    difficulty: SessionDifficulty.A2,
  },
  {
    term: 'prepare',
    definition: 'to get ready',
    example: 'They ???? dinner after work.',
    difficulty: SessionDifficulty.A2,
  },
  {
    term: 'favorite',
    definition: 'the one you like the most',
    example: 'Blue is my ???? color.',
    difficulty: SessionDifficulty.A2,
  },
  {
    term: 'practice',
    definition: 'to do something often to get better at it',
    example: 'She ????s the piano every day.',
    difficulty: SessionDifficulty.A2,
  },
  {
    term: 'achieve',
    definition: 'to successfully reach a goal',
    example: 'He worked hard to ???? success.',
    difficulty: SessionDifficulty.B1,
  },
  {
    term: 'debate',
    definition: 'a formal discussion of different opinions',
    example: 'The class held a ???? on climate policy.',
    difficulty: SessionDifficulty.B1,
  },
  {
    term: 'measure',
    definition: 'to find the size or amount of something',
    example: 'We ???? the room before buying furniture.',
    difficulty: SessionDifficulty.B1,
  },
  {
    term: 'organize',
    definition: 'to arrange things in order',
    example: 'She will ???? the files by date.',
    difficulty: SessionDifficulty.B1,
  },
  {
    term: 'consider',
    definition: 'to think about something carefully',
    example: 'Please ???? the consequences.',
    difficulty: SessionDifficulty.B1,
  },
  {
    term: 'improve',
    definition: 'to make something better',
    example: 'He wants to ???? his English.',
    difficulty: SessionDifficulty.B1,
  },
  {
    term: 'predict',
    definition: 'to say what will happen in the future',
    example: 'Experts ???? more rain tomorrow.',
    difficulty: SessionDifficulty.B1,
  },
  {
    term: 'support',
    definition: 'to help or give assistance',
    example: 'Her friends ???? her decision.',
    difficulty: SessionDifficulty.B1,
  },
  {
    term: 'resource',
    definition: 'a useful supply or source',
    example: 'Time is our most valuable ????.',
    difficulty: SessionDifficulty.B1,
  },
  {
    term: 'eventually',
    definition: 'after some time',
    example: 'They ???? found the right solution.',
    difficulty: SessionDifficulty.B1,
  },
  {
    term: 'assume',
    definition: 'to accept something as true without proof',
    example: 'Do not ???? the train is late.',
    difficulty: SessionDifficulty.B2,
  },
  {
    term: 'beneficial',
    definition: 'producing good results',
    example: 'Exercise is ???? to health.',
    difficulty: SessionDifficulty.B2,
  },
  {
    term: 'controversy',
    definition: 'a strong public disagreement',
    example: 'The proposal sparked ????.',
    difficulty: SessionDifficulty.B2,
  },
  {
    term: 'evaluate',
    definition: 'to judge the quality or value of something',
    example: 'We ???? the program every year.',
    difficulty: SessionDifficulty.B2,
  },
  {
    term: 'maintain',
    definition: 'to keep something in good condition',
    example: 'It is hard to ???? focus all day.',
    difficulty: SessionDifficulty.B2,
  },
  {
    term: 'interpret',
    definition: 'to explain the meaning of something',
    example: 'How do you ???? the results?',
    difficulty: SessionDifficulty.B2,
  },
  {
    term: 'significant',
    definition: 'important or noticeable',
    example: 'There was a ???? increase in costs.',
    difficulty: SessionDifficulty.B2,
  },
  {
    term: 'contribute',
    definition: 'to help make something happen',
    example: 'Many factors ???? to success.',
    difficulty: SessionDifficulty.B2,
  },
  {
    term: 'clarify',
    definition: 'to make something easier to understand',
    example: 'Can you ???? your last point?',
    difficulty: SessionDifficulty.B2,
  },
  {
    term: 'implement',
    definition: 'to put a plan into action',
    example: 'They will ???? the new policy next week.',
    difficulty: SessionDifficulty.B2,
  },
  {
    term: 'allocate',
    definition: 'to distribute resources for a purpose',
    example: 'We ???? funds to research every year.',
    difficulty: SessionDifficulty.C1,
  },
  {
    term: 'coherent',
    definition: 'logical and well organized',
    example: 'Her argument was clear and ????.',
    difficulty: SessionDifficulty.C1,
  },
  {
    term: 'constrain',
    definition: 'to limit or restrict',
    example: 'The budget will ???? our options.',
    difficulty: SessionDifficulty.C1,
  },
  {
    term: 'deduce',
    definition: 'to reach a conclusion from evidence',
    example: 'From the data, we can ???? a pattern.',
    difficulty: SessionDifficulty.C1,
  },
  {
    term: 'fluctuate',
    definition: 'to change often and unpredictably',
    example: 'Prices ???? throughout the year.',
    difficulty: SessionDifficulty.C1,
  },
  {
    term: 'integrate',
    definition: 'to combine into a whole',
    example: 'We ???? feedback into the final plan.',
    difficulty: SessionDifficulty.C1,
  },
  {
    term: 'notwithstanding',
    definition: 'in spite of',
    example: '???? the delays, we finished on time.',
    difficulty: SessionDifficulty.C1,
  },
  {
    term: 'resilient',
    definition: 'able to recover quickly',
    example: 'The system is ???? under stress.',
    difficulty: SessionDifficulty.C1,
  },
  {
    term: 'substantiate',
    definition: 'to support with evidence',
    example: 'The report will ???? the claims.',
    difficulty: SessionDifficulty.C1,
  },
  {
    term: 'sustain',
    definition: 'to keep something going',
    example: 'They worked to ???? growth over time.',
    difficulty: SessionDifficulty.C1,
  },
  {
    term: 'ameliorate',
    definition: 'to make something better',
    example: 'New guidelines aim to ???? risks.',
    difficulty: SessionDifficulty.C2,
  },
  {
    term: 'circumspect',
    definition: 'careful to consider all circumstances',
    example: 'She remained ???? in her response.',
    difficulty: SessionDifficulty.C2,
  },
  {
    term: 'disseminate',
    definition: 'to spread information widely',
    example: 'They will ???? the findings quickly.',
    difficulty: SessionDifficulty.C2,
  },
  {
    term: 'equivocal',
    definition: 'open to more than one interpretation',
    example: 'His answer was deliberately ????.',
    difficulty: SessionDifficulty.C2,
  },
  {
    term: 'inexorable',
    definition: 'impossible to stop or prevent',
    example: 'The ???? rise continued.',
    difficulty: SessionDifficulty.C2,
  },
  {
    term: 'magnanimous',
    definition: 'generous and forgiving',
    example: 'He was ???? in victory.',
    difficulty: SessionDifficulty.C2,
  },
  {
    term: 'obfuscate',
    definition: 'to make something unclear',
    example: 'The memo tried to ???? the issue.',
    difficulty: SessionDifficulty.C2,
  },
  {
    term: 'proliferate',
    definition: 'to increase rapidly in number',
    example: 'Startups can ???? across the city.',
    difficulty: SessionDifficulty.C2,
  },
  {
    term: 'quintessential',
    definition: 'the most perfect example of something',
    example: 'She is the ???? leader.',
    difficulty: SessionDifficulty.C2,
  },
  {
    term: 'ubiquitous',
    definition: 'present everywhere at the same time',
    example: 'Smartphones are ???? now.',
    difficulty: SessionDifficulty.C2,
  },
];
