type Query {
  user(id: ID!): User
  students: [User!]!
}

type Mutation {
  createUser(createUserInput: CreateUserInput): User
  login(loginInput: LoginInput): AuthPayload
  refreshToken: AuthPayload
  logout: Boolean!
}

enum Role {
  STUDENT
  TEACHER
  ADMIN
}

type User {
  id: Int!
  name: String!
  displayName: String! 
  role: Role!
}

type AuthPayload {
  accessToken: String!
}

input CreateUserInput {
  name: String!
  displayName: String
  password: String!
  role: Role!
}

input LoginInput {
  name: String!
  password: String!
}
